apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix-deploymentpod
spec:
  replicas: 4
  template:
    metadata:
      name: ngnix-deploy
      labels:
        app: ngnix
    spec:
      containers:
        - name: ngnix-container
          image: jeevanbg/new_app:tag26
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: ngnix

---
apiVersion: v1
kind: Service
metadata:
  name: my-nodeport
spec:
  type: Nodeport
  selector:
    app: ngnix
  ports:
    - name: http
      port: 8090
      targetPort: 80
      nodePort: 30002
 


 
