apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix-deploymentpod
spec:
  replicas: 4
  template:
    metadata:
      name: ngnix-deploy
      labels:
        app: nginx
    spec:
      containers:
        - name: ngnix-container
          image: jeevanbg/new_app:tag26
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: ngnix



 
